name: Todohub Workflow
on: [push, pull_request]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  todohub-job:
    runs-on: ubuntu-latest
    steps:
      - name: Todohub
        id: todohub
        uses: todos-in/todohub@main
